name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]
    paths: ./To-do-list-app*
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and Push to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-image:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-image:latest
    # - name: ACR build
    #   id: acr
    #   uses: azure/acr-build@v1
    #   with:
    #     service_principal: ${{ secrets.service_principal }}
    #     service_principal_password: ${{ secrets.service_principal_password }}
    #     tenant: ${{ secrets.tenant }}
    #     registry: ${{ secrets.registry }}
    #     repository: ${{ secrets.repository }}
    #     image: image
    #     git_access_token: ${{ secrets.git_access_token }}
    #     folder: src/docker
    #     dockerfile: ../../Dockerfile
    #     branch: main
    #     build_args: '[{"arg_one":"value_one"}, {"arg_two":"value_two"}]'
